# Alacritty Config
#
# See: https://github.com/alacritty/alacritty#configuration
# See: https://github.com/alacritty/alacritty/blob/master/alacritty.yml
# See: https://defkey.com/alacritty-0-9-shortcuts
# See: https://arslan.io/2018/02/05/gpu-accelerated-terminal-alacritty/

[mouse]
hide_when_typing = true

[colors.primary]
background = "0x0f111a"
foreground = "0xe6edf3"

[font]
size = 10.0

[font.bold]
family = "FiraCode Nerd Font"
style = "SemiBold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"

[[keyboard.bindings]]
chars = "â‚¬"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Super"

# Start tmux https://pawelgrzybek.com/autostart-tmux-on-alacritty-launch/
[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
# startup_mode: Fullscreen
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5
